- name: Install System Packages 1 (build-essential, git, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "git", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: ["i3","dconf-editor", "moreutils", "stow"]
  tags:
    - install
    - core
