- name: Download MS product repo
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
  tags:
    - dotnet
- name: Install MS product repo
  apt: deb=/tmp/packages-microsoft-prod.deb
  become: true
  tags:
    - dotnet
- name: Make sure https is supported
  apt:
    name: apt-transport-https
    state: present
    update_cache: no
  tags:
    - dotnet
- name: Install dotnet sdk
  apt:
    name: dotnet-sdk-7.0
    state: present
    update-cache: yes
  tags:
    - dotnet
